// <auto-generated />
namespace WebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationbtwenorderandcustomerusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationbtwenorderandcustomerusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201612081349489_relation btwen order and customer(users)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
