// <auto-generated />
namespace WebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removemandatorybetweenproductandcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removemandatorybetweenproductandcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201612031856092_remove mandatory between product and category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
