// <auto-generated />
namespace WebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductQuantityMinus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductQuantityMinus));
        
        string IMigrationMetadata.Id
        {
            get { return "201702201132371_Product Quantity Minus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
